/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2020-06-25 11:52:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ordertemp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/order/../inc/bottom.jsp", Long.valueOf(1593085911696L));
    _jspx_dependants.put("/order/../inc/top.jsp", Long.valueOf(1593085911697L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\t<!DOCTYPE html>\r\n");
      out.write("\t<html lang=\"zxx\" class=\"no-js\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<!-- Mobile Specific Meta -->\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\t\t<!-- Favicon-->\r\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/img/fav.png\">\r\n");
      out.write("\t\t<!-- Author Meta -->\r\n");
      out.write("\t\t<meta name=\"author\" content=\"colorlib\">\r\n");
      out.write("\t\t<!-- Meta Description -->\r\n");
      out.write("\t\t<meta name=\"description\" content=\"\">\r\n");
      out.write("\t\t<!-- Meta Keyword -->\r\n");
      out.write("\t\t<meta name=\"keywords\" content=\"\">\r\n");
      out.write("\t\t<!-- meta character set -->\r\n");
      out.write("\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t<!-- Site Title -->\r\n");
      out.write("\t\t<title>Marco</title>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("\t\t<link href=\"https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700\" rel=\"stylesheet\"> \r\n");
      out.write("\t\t\t<!--\r\n");
      out.write("\t\t\tCSS\r\n");
      out.write("\t\t\t============================================= -->\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/linearicons.css\">\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/font-awesome.min.css\">\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/bootstrap.css\">\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/magnific-popup.css\">\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/jquery-ui.css\">\t\t\t\t\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/nice-select.css\">\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/animate.min.css\">\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/owl.carousel.css\">\t\t\t\t\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/main.css\">\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/other.css\">\r\n");
      out.write("\t\t</head>\r\n");
      out.write("\t\t<body>\t\r\n");
      out.write("\t\t\t<header id=\"header\">\r\n");
      out.write("\t\t\t\t<div class=\"header-top\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t  \t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t\t\t\t\t\t      <div id=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t        <a href=\"#\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/img/logo.png\" alt=\"\" title=\"\" /></a>\r\n");
      out.write("\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t      \r\n");
      out.write("\t\t\t\t  \t\t</div>\t\t\t  \t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"container main-menu\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row align-items-center justify-content-center d-flex\">\t\t\t\r\n");
      out.write("\t\t\t\t      <nav id=\"nav-menu-container\">\r\n");
      out.write("\t\t\t\t        <ul class=\"nav-menu\">\r\n");
      out.write("\t\t\t\t          <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp#home\">Home</a></li>\r\n");
      out.write("\t\t\t\t          <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp#about\">About</a></li>\r\n");
      out.write("\t\t\t\t          <li><a href=\"#\">Menu</a></li>\r\n");
      out.write("\t\t\t\t          <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp#order\">Order</a></li>\r\n");
      out.write("\t\t\t\t          <li><a href=\"#\">Find a Store</a></li>\r\n");
      out.write("\t\t\t\t          <li><a href=\"#\">Review</a></li>\r\n");
      out.write("\t\t\t\t          <li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t          <li class=\"menu-has-children\"><a href=\"\">My</a>\r\n");
      out.write("\t\t\t\t            <ul>\r\n");
      out.write("\t\t\t\t              <li><a href=\"#\">login</a></li>\r\n");
      out.write("\t\t\t\t              <li><a href=\"#\">my page</a></li>\r\n");
      out.write("\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t          </li>\t\r\n");
      out.write("\t\t\t\t          <li><a href=\"#\">cart</a></li>\r\n");
      out.write("\t\t\t\t          <!-- <li class=\"menu-has-children\"><a href=\"\">Pages</a>\r\n");
      out.write("\t\t\t\t            <ul>\r\n");
      out.write("\t\t\t\t            \t  <li><a href=\"#\">Elements</a></li>\r\n");
      out.write("\t\t\t\t\t\t          <li class=\"menu-has-children\"><a href=\"\">Level 2 </a>\r\n");
      out.write("\t\t\t\t\t\t            <ul>\r\n");
      out.write("\t\t\t\t\t\t              <li><a href=\"#\">Item One</a></li>\r\n");
      out.write("\t\t\t\t\t\t              <li><a href=\"#\">Item Two</a></li>\r\n");
      out.write("\t\t\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t\t\t          </li>\t\t\t\t\t                \t\t\r\n");
      out.write("\t\t\t\t            </ul>\r\n");
      out.write("\t\t\t\t          </li>\t -->\t\t\t\t          \t\t\t\t\t          \t\t          \r\n");
      out.write("\t\t\t\t        </ul>\r\n");
      out.write("\t\t\t\t      </nav><!-- #nav-menu-container -->\t\t\t\t\t      \t\t  \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</header><!-- #header -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      out.write('\r');
      out.write('\n');

	

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/order.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/order.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<section class=\"banner-area\" id=\"home\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row fullscreen align-items-center justify-content-between\">\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("<h2 style=\"text-align: center\">Select yours</h2>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<div class=\"mySlides\">\r\n");
      out.write("\t\t<div class=\"numbertext\">1 / 4</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<section class=\"toppingselect\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><h3>사이즈</h3></td>\r\n");
      out.write("\t\t\t\t\t\t<td><h4>하나를 선택해주세요</h4></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!--사이즈 선택 반복문  -->\r\n");
      out.write("\t\t\t\t\t");

						String[] sizeArr={"regular","large","family"};
						String[] sizeNameArr={"Regular","Large","Family"};
						String[] sizeImgArr={"","",""};
						for(int i=0;i<sizeArr.length;i++){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><img alt=\"");
      out.print(sizeArr[i] );
      out.write("\" src=\"");
      out.print(request.getContextPath() );
      out.write("/img/order/d1.jpg\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"radio\" name=\"size\" value=\"");
      out.print(sizeArr[i] );
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><h5>");
      out.print(sizeNameArr[i] );
      out.write("</h5></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><br></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><h3>도우</h3></td>\r\n");
      out.write("\t\t\t\t\t\t<td><h4>하나를 선택해주세요</h4></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!--도우 선택 반복문  -->\r\n");
      out.write("\t\t\t\t\t");

						String[] doughArr={"original","napoli","thin"};
						String[] doughNameArr={"기본 도우","나폴리 도우","씬 도우"};
						String[] doughImgArr={"","",""};
						for(int i=0;i<doughArr.length;i++){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><img alt=\"");
      out.print(doughArr[i] );
      out.write("\" src=\"");
      out.print(request.getContextPath() );
      out.write("/img/order/d1.jpg\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"radio\" name=\"dough\" value=\"");
      out.print(doughArr[i] );
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><h5>");
      out.print(doughNameArr[i] );
      out.write("</h5></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><h3><br></h3></td>\r\n");
      out.write("\t\t\t\t\t\t<td><h4></h4></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><h3>크러스트</h3></td>\r\n");
      out.write("\t\t\t\t\t\t<td><h4>하나를 선택해주세요</h4></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!--크러스트 선택 반복문  -->\r\n");
      out.write("\t\t\t\t\t");

						String[] crustArr={"normal","cheese","bite","gold"};
						String[] crustNameArr={"기본","치즈 크러스트","치즈 바이트","골드 크런치"};
						String[] crustImgArr={"","",""};
						for(int i=0;i<crustArr.length;i++){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><img alt=\"");
      out.print(crustArr[i] );
      out.write("\" src=\"");
      out.print(request.getContextPath() );
      out.write("/img/order/d1.jpg\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"radio\" name=\"crust\" value=\"");
      out.print(crustArr[i] );
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><h5>");
      out.print(crustNameArr[i] );
      out.write("</h5></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"mySlides\">\r\n");
      out.write("\t\t<div class=\"numbertext\">2 / 4</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t<section class=\"toppingselect\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><h3>소스</h3></td>\r\n");
      out.write("\t\t\t\t\t\t<td><h4>선택</h4></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!--소스 선택 반복문  -->\r\n");
      out.write("\t\t\t\t\t");

						String[] sauceArr={"tomato","basil","honey", "white"};
						String[] sauceNameArr={"토마토","바질","허니(꿀)","까르보나라"};
						String[] sauceImgArr={"","",""};
						for(int i=0;i<sauceArr.length;i++){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><img alt=\"");
      out.print(sauceArr[i] );
      out.write("\" src=\"");
      out.print(request.getContextPath() );
      out.write("/img/order/d1.jpg\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"radio\" name=\"sauce\" value=\"");
      out.print(sauceArr[i] );
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><h5>");
      out.print(sauceNameArr[i] );
      out.write("</h5></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"mySlides\">\r\n");
      out.write("\t\t<div class=\"numbertext\">3 / 4</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<section class=\"toppingselect\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><h3>토핑</h3></td>\r\n");
      out.write("\t\t\t\t\t\t<td><h4>선택</h4></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!--토핑 선택 반복문  -->\r\n");
      out.write("\t\t\t\t\t");

						String[] toppArr={"mushroom","ham","cheese","shrimp","olive","paprika",
								"onion","pepperoni","bulgogi","potato","sweetpotato","bacon"};
						String[] toppNameArr={"버섯","햄","치즈","새우","올리브","파프리카","양파","페페로니",
								"불고기","감자","고구마","베이컨"};
						String[] toppImgArr={"","",""};
						for(int i=0;i<toppArr.length;i++){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><img alt=\"");
      out.print(toppArr[i] );
      out.write("\" src=\"");
      out.print(request.getContextPath() );
      out.write("/img/order/d1.jpg\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"topping\" value=\"");
      out.print(toppArr[i]);
      out.write("\" ></td>\r\n");
      out.write("\t\t\t\t\t\t<td><select name=\"");
      out.print(toppArr[i] );
      out.write("\" style=\"visibility:hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"1\">조금</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"2\">보통</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"3\">많이</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"4\">아주 많이</option>\r\n");
      out.write("\t\t\t\t\t\t   \t</select> \r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><h5>");
      out.print(toppNameArr[i] );
      out.write("</h5></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"mySlides\">\r\n");
      out.write("\t\t<div class=\"numbertext\">4 / 4</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<section class=\"toppingselect\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><h3>토핑</h3></td>\r\n");
      out.write("\t\t\t\t\t\t<td><h4>선택</h4></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!--사이드 선택 반복문  -->\r\n");
      out.write("\t\t\t\t\t");

						String[] sideArr={"cola","fanta","trevi", "chickenwing", "potatofries","spaghetti"};
						String[] sideNameArr={"콜라","환타","탄산수", "버팔로윙", "감자 튀김","스파게티"};
						String[] sideImgArr={"","",""};
						
						for(int i=0;i<sideArr.length;i++){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><img alt=\"");
      out.print(sideArr[i] );
      out.write("\" src=\"");
      out.print(request.getContextPath() );
      out.write("/img/order/d1.jpg\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"checkbox\" name=\"side\" value=\"");
      out.print(sideArr[i]);
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><select name=\"");
      out.print(sideArr[i] );
      out.write("\" style=\"visibility:hidden\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"1\">1</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"2\">2</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"3\">3</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"4\">4</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"5\">직접입력</option>\r\n");
      out.write("\t\t\t\t\t\t   \t</select> \r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><h5>");
      out.print(sideNameArr[i] );
      out.write("</h5></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"caption-container\">\r\n");
      out.write("\t\t<p id=\"caption\"></p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t<div class=\"selcate\">\r\n");
      out.write("\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t<img class=\"demo cursor\" src=\"");
      out.print(request.getContextPath() );
      out.write("/img/order/doughback.jpg\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 100%\" onclick=\"currentSlide(1)\" alt=\"도우 & 크러스트\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t<img class=\"demo cursor\" src=\"");
      out.print(request.getContextPath() );
      out.write("/img/order/sauceback.jpg\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 100%\" onclick=\"currentSlide(2)\" alt=\"소스\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t<img class=\"demo cursor\" src=\"");
      out.print(request.getContextPath() );
      out.write("/img/order/toppingback.jpg\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 100%\" onclick=\"currentSlide(3)\" alt=\"토핑\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t<img class=\"demo cursor\" src=\"");
      out.print(request.getContextPath() );
      out.write("/img/order/sideback.jpg\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 100%\" onclick=\"currentSlide(4)\" alt=\"사이드\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"floating\"> \r\n");
      out.write("<!--주문 리모컨  -->\r\n");
      out.write("<div>\r\n");
      out.write("\t<table id=\"remoteTable\">\r\n");
      out.write("\t\t<tr id=\"remoteTable\">\r\n");
      out.write("\t\t\t<td>종류</td>\r\n");
      out.write("\t\t\t<td>선택</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>사이즈</td>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>도우</td>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>소스</td>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("<img src=\"");
      out.print(request.getContextPath() );
      out.write("/img/order/orderbt.jpg\" alt=\"주문버튼\">\t\r\n");
      out.write("<img src=\"");
      out.print(request.getContextPath() );
      out.write("/img/order/cartbt.jpg\" alt=\"주문버튼\">\t\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar slideIndex = 1;\r\n");
      out.write("\tshowSlides(slideIndex);\r\n");
      out.write("\r\n");
      out.write("\tfunction plusSlides(n) {\r\n");
      out.write("\t\tshowSlides(slideIndex += n);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction currentSlide(n) {\r\n");
      out.write("\t\tshowSlides(slideIndex = n);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction showSlides(n) {\r\n");
      out.write("\t\tvar i;\r\n");
      out.write("\t\tvar slides = document.getElementsByClassName(\"mySlides\");\r\n");
      out.write("\t\tvar dots = document.getElementsByClassName(\"demo\");\r\n");
      out.write("\t\tvar captionText = document.getElementById(\"caption\");\r\n");
      out.write("\t\tif (n > slides.length) {\r\n");
      out.write("\t\t\tslideIndex = 1\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (n < 1) {\r\n");
      out.write("\t\t\tslideIndex = slides.length\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfor (i = 0; i < slides.length; i++) {\r\n");
      out.write("\t\t\tslides[i].style.display = \"none\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfor (i = 0; i < dots.length; i++) {\r\n");
      out.write("\t\t\tdots[i].className = dots[i].className.replace(\" active\", \"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tslides[slideIndex - 1].style.display = \"block\";\r\n");
      out.write("\t\tdots[slideIndex - 1].className += \" active\";\r\n");
      out.write("\t\tcaptionText.innerHTML = dots[slideIndex - 1].alt;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- start footer Area -->\t\t\r\n");
      out.write("\t\t\t<footer class=\"footer-area\">\r\n");
      out.write("\t\t\t\t<div class=\"footer-widget-wrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row section-gap\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-4  col-md-6 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"single-footer-widget\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>Opening Hours</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"hr-list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"d-flex justify-content-between\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Monday - Friday</span> <span>08.00 am - 10.00 pm</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"d-flex justify-content-between\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Saturday</span> <span>08.00 am - 10.00 pm</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"d-flex justify-content-between\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Sunday</span> <span>08.00 am - 10.00 pm</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</li>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-4  col-md-6 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"single-footer-widget\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>Contact Us</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t56/8, los angeles, rochy beach, Santa monica, United states of america - 1205\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"number\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t012-6532-568-9746 <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t012-6532-569-9748\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-4  col-md-6 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"single-footer-widget\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>Newsletter</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>You can trust us. we only send promo offers, not a single spam.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"d-flex flex-row\" id=\"mc_embed_signup\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  <form class=\"navbar-form\" action=\"https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    <div class=\"input-group add-on align-items-center d-flex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      \t<input class=\"form-control\" name=\"EMAIL\" placeholder=\"Your Email address\" onfocus=\"this.placeholder = ''\" onblur=\"this.placeholder = 'Your Email address'\" required=\"\" type=\"email\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"position: absolute; left: -5000px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input name=\"b_36c4fd991d266f23781ded980_aefe40901a\" tabindex=\"-1\" value=\"\" type=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      <div class=\"input-group-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t        <button class=\"genric-btn\"><span class=\"lnr lnr-arrow-right\"></span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t      <div class=\"info mt-20\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  </form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"footer-bottom-wrap\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row footer-bottom d-flex justify-content-between align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"col-lg-8 col-mdcol-sm-6 -6 footer-text m-0\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a> &amp; distributed by <a href=\"https://themewagon.com\" target=\"_blank\">ThemeWagon</a>\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"col-lg-4 col-mdcol-sm-6 -6 social-icons text-right\">\r\n");
      out.write("\t                            <li><a href=\"#\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("\t                            <li><a href=\"#\"><i class=\"fa fa-twitter\"></i></a></li>\r\n");
      out.write("\t                            <li><a href=\"#\"><i class=\"fa fa-dribbble\"></i></a></li>\r\n");
      out.write("\t                            <li><a href=\"#\"><i class=\"fa fa-behance\"></i></a></li>           \r\n");
      out.write("\t                        </ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("\t\t\t<!-- End footer Area -->\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/vendor/jquery-2.2.4.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/popper.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/vendor/bootstrap.min.js\"></script>\t\t\t\r\n");
      out.write("\t\t\t<script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA\"></script>\t\t\r\n");
      out.write(" \t\t\t<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-ui.js\"></script>\t\t\t\t\t\r\n");
      out.write("  \t\t\t<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/easing.min.js\"></script>\t\t\t\r\n");
      out.write("\t\t\t<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/hoverIntent.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/superfish.min.js\"></script>\t\r\n");
      out.write("\t\t\t<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery.magnific-popup.min.js\"></script>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery.nice-select.min.js\"></script>\t\t\t\t\t\r\n");
      out.write("\t\t\t<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/owl.carousel.min.js\"></script>\t\t\t\r\n");
      out.write("            <script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/isotope.pkgd.min.js\"></script>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/mail-script.js\"></script>\t\r\n");
      out.write("\t\t\t<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/main.js\"></script>\t\r\n");
      out.write("\t\t</body>\r\n");
      out.write("\t</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
